# Generated by Django 2.2.4 on 2019-08-14 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preg', models.IntegerField()),
                ('plas', models.IntegerField()),
                ('press', models.IntegerField()),
                ('skin', models.IntegerField()),
                ('test', models.IntegerField()),
                ('mass', models.DecimalField(decimal_places=1, max_digits=100)),
                ('pedi', models.DecimalField(decimal_places=3, max_digits=10)),
                ('age', models.IntegerField()),
                ('clase', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=100)),
                ('preg', models.IntegerField()),
                ('plas', models.IntegerField()),
                ('press', models.IntegerField()),
                ('skin', models.IntegerField()),
                ('test', models.IntegerField()),
                ('mass', models.DecimalField(decimal_places=1, max_digits=100)),
                ('pedi', models.DecimalField(decimal_places=3, max_digits=10)),
                ('age', models.IntegerField()),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
